### ISSUE TITLE
[Bug]: Not able to install bundle for pimcore 10.4.1

### ISSUE THREAD

**Issue by rajesh17692pimcore** [pimcore/object-merger#11]
### Expected behavior

should be able to install the bundle on pimcore 10.4.1

### Actual behavior

asks to downgrade pimcore 10.4.0

### Steps to reproduce

upgrade pimcore from 10.4.0 to 10.4.1
try to install object merger bundle

**Comment by aryaantony92** [comment]
@rajesh17692pimcore Could you please give the screenshot of the error you got ? I tried to install the object merger bundle after updating pimcore and it is installed.

**Comment by aryaantony92** [comment]
@rajesh17692pimcore  Just a gentle reminder. Could you please share the screenshot of the error ?

**Comment by dvesh3** [comment]
Closed due to inactivity. please feel free to come back with reproducible steps. thanks!
