### ISSUE TITLE
[Bug]: Comparing objects throws "not supported"

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/object-merger#21]
### Expected behavior

It should be possible to compare two DataObjects, and any error message should be clear to the user what is wrong.

### Actual behavior

![image](https://user-images.githubusercontent.com/279826/204248533-30bf130e-5e6e-4379-b42a-0c81892ac758.png)

```trace
Timestamp: Mon Nov 28 2022 10:58:28 GMT+0100 (Central European Standard Time)
Status: 500 | Internal Server Error
URL: /admin/elementsobjectmerger/admin/diff
Method: post
Message: not supported
Trace: 
in /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Classificationstore.php:859
#0 /var/www/pimcore/vendor/pimcore/object-merger/src/Controller/AdminController.php(47): Pimcore\Model\DataObject\ClassDefinition\Data\Classificationstore->getDiffDataForEditmode(Object(Pimcore\Model\DataObject\Classificationstore), Object(App\Model\DataObject\Product))
pimcore/pimcore#1 /var/www/pimcore/vendor/pimcore/object-merger/src/Controller/AdminController.php(57): Pimcore\Bundle\ObjectMergerBundle\Controller\AdminController->getDiffDataForField(Object(App\Model\DataObject\Product), 'dataStoreEnergy', Object(Pimcore\Model\DataObject\ClassDefinition\Data\Classificationstore))
pimcore/pimcore#2 /var/www/pimcore/vendor/pimcore/object-merger/src/Controller/AdminController.php(133): Pimcore\Bundle\ObjectMergerBundle\Controller\AdminController->getDiffDataForObject(Object(App\Model\DataObject\Product), false)
pimcore/pimcore#3 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(153): Pimcore\Bundle\ObjectMergerBundle\Controller\AdminController->diffAction(Object(Symfony\Component\HttpFoundation\Request))
pimcore/pimcore#4 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
pimcore/pimcore#5 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
pimcore/pimcore#6 /var/www/pimcore/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
pimcore/pimcore#7 {main}
```

### Steps to reproduce

1. Open the dialogue 

2. Select two objects 
![image](https://user-images.githubusercontent.com/279826/204248756-43a9bd77-def1-400f-989f-c73d77e2d5fd.png)

3. Compare.

**Comment by brusch** [comment]
Moved to the right repo 😊

**Comment by fashxp** [comment]
works for 'any' object in demo, more detailed information appreciated.

**Comment by NiklasBr** [comment]
Here is a screen recording:

https://user-images.githubusercontent.com/279826/204253773-848ae281-c8be-4b7b-8be3-8743633f171a.mov

**Comment by NiklasBr** [comment]
@fashxp I can reproduce the issue on demo.pimcore.fun:


https://user-images.githubusercontent.com/279826/204282822-b5b38da0-ed21-46c9-99dc-e36497ee4d86.mov

**Comment by mattamon** [comment]
@brusch, @fashxp, the classification store does not support ```php getDiffDataForEditmode``` or ```phpgetDiffDataFromEditmode```. https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/ClassDefinition/Data/Classificationstore.php#L723

How should we approach this? It is not a object-merger problem per se. Of course  we can just catch the exception that is thrown in the classifcation store or maybe we do not throw an exception and instead return like a "classification store data cannot be compared"?

Wdyt?
Maybe we find a way to support the classificationstore data? I guess the not support exception causes other problems too.

**Comment by NiklasBr** [comment]
What was the design motivation for not supporting Classification Stores here?

**Comment by fashxp** [comment]
Just time... we apprechiate any contributions...

**Comment by NiklasBr** [comment]
Good to know it was just unfinished, it was just so hard to know from what little info was available. Since there was no documentation I could find or no comments in the code referenced I wondered if it was maybe "working as intended"…
