### ISSUE TITLE
Customer Duplicates Service # Duplicates View # Merge

### ISSUE THREAD

**Issue by nexus23** [pimcore/object-merger#7]
I have discover two major failures in this bundle, which is also needed by PIM CMF
When i merge via CMF > Customer duplicates
Error
Message: Warning: Undefined array key "value"
Trace: in /vendor/pimcore/object-merger/src/Controller/AdminController.php:163

if I correct this provisionally with
$merged['value2'] = $entry2['value'] ?? null;

then i got the next failure:

Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch(): Argument #1 ($event) must be of type object, string given, called in /vendor/pimcore/object-merger/src/Controller/AdminController.php on line 275

CONFIGURATION::

PIM 10.0.7
CMF 3.2.0
ObjektMerger 3.0.3

**Comment by dvesh3** [comment]
- Warning: Undefined array key "value" issue is fixed by #10
- Argument ($event) must be of type object... was fixed already in https://github.com/pimcore/object-merger/pull/8

**Comment by dvesh3** [comment]
Fixed by #10
